C# Web - September 2018/Eventures/Eventures.Web/Controllers/EventsController.cs
namespace Eventures.Web.Controllers
{
    using Data;
    using Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.Contracts;
    using Services.Models;

    public class EventsController : Controller
    {
        private readonly EventuresDbContext db;
        private readonly IEventService service;

        public EventsController(EventuresDbContext db, IEventService service)
        {
            this.db = db;
            this.service = service;
        }

        public IActionResult All(int page = 1)
            => this.View(new EventListingViewModel
            {
                Events = this.service.All(page),
                TotalEvents = this.service.Total(),
                CurrentPage = page
            });

        public IActionResult MyEvents(string id)
        {
            var result = this.service.ByUser(id);

            return this.View(result);
        }

        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {
            return this.View();
        }
     
        [HttpPost]
        public IActionResult Create(
            [Bind("Name,Start,End,TotalTickets,PricePerTicket")] EventModel event_)
        {
            // TODO
            var eventDb = new Event
            {
                Name = event_.Name,
                Start = event_.Start,
                End = event_.End,
                TotalTickets = event_.TotalTickets,
                PricePerTicket = event_.PricePerTicket
            };

            this.service.Create(eventDb);

            return this.RedirectToAction(nameof(All));
        }
    }
}

C# Web - September 2018/Eventures/Eventures.Web/Controllers/OrdersController.cs
namespace Eventures.Web.Controllers
{
    using Data;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Services.Contracts;

    public class OrdersController : Controller
    {
        private readonly EventuresDbContext db;
        private readonly IOrderService service;
        
        public OrdersController(EventuresDbContext db, IOrderService service)
        {
            this.db = db;
            this.service = service;
        }

        [Authorize(Roles = "ADMIN")]
        public IActionResult All()
        {
            var allOrders = this.service.All();
            return this.View(allOrders);
        }

        [HttpPost]
        public IActionResult Order(int tickets, string username, string eventName)
        {
            this.service.Order(tickets, username, eventName);

            return this.RedirectToAction(nameof(All));
        }
    }
}

C# Web - September 2018/Eventures/Eventures.Web/Views/Shared/_Layout.cshtml
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eventures</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-fixed-top" style="background-color: #AFEEEE">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" style="font-weight: bold; color: black">Eventures</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index" style="color: black; font-weight: bold">Home</a></li>

                    <!--Administrator have access to Events and Orders-->
                    <!--TODO: FIX THIS-->
                    @if (this.User.IsInRole("ADMIN"))
                    {
                        <!--Events-->
                        <li class="dropdown">
                            <a style="color: black; font-weight: bold" class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Events<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a asp-area="" asp-controller="Events" asp-action="All">All Events</a></li>
                                <li><a asp-area="" asp-controller="Events" asp-action="MyEvents" asp-route-id="@this.UserManager.GetUserId(this.User)">My Events</a></li>
                                <li><a asp-area="" asp-controller="Events" asp-action="Create">Create Event</a></li>
                            </ul>
                        </li>

                        <!--Orders-->
                        <li class="dropdown">
                            <a style="color: black; font-weight: bold" class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Orders<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a asp-area="" asp-controller="Orders" asp-action="All">All Orders</a></li>
                            </ul>
                        </li>
                    }

                    <!--User have access to Events-->
                    @if (this.User.IsInRole("USER"))
                    {
                        <!--Events-->
                        <li class="dropdown">
                            <a style="color: black; font-weight: bold" class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Events<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a asp-area="" asp-controller="Events" asp-action="All">All Events</a></li>
                                <li><a asp-area="" asp-controller="Events" asp-action="MyEvents" asp-route-id="@this.UserManager.GetUserId(this.User)">My Events</a></li>
                            </ul>
                        </li>
                    }

                    </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <footer style="background-color: #AFEEEE">
            <p style="text-align: center; padding: 10px">&copy; CopyRight Eventures Inc. 2018-2018. All Rights Reserved.</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>